#!/usr/bin/env php
<?php

use Amp\File\StatCache;
use Amp\Loop;
use Vajexal\HotReload\Config;
use Vajexal\HotReload\ConfigException;
use Vajexal\HotReload\HotReloadWatcher;
use Vajexal\HotReload\PathFilter\GlobPathFilter;

require_once 'vendor/autoload.php';

try {
    $config = Config::createFromArgv();
} catch (ConfigException $e) {
    echo 'Usage: ./vendor/bin/hot-reload server.php', PHP_EOL;

    exit(1);
}

Loop::run(function () use ($config) {
    StatCache::ttl(0);

    $pathFilter = new GlobPathFilter;

    foreach ($config->getExcludePatterns() as $pattern) {
        $pathFilter->exclude($pattern);
    }

    $pathFilter->filePattern($config->getFilePattern());

    $hotReloadWatcher = new HotReloadWatcher('.', [PHP_BINARY, ...$config->getCommand()], $config, $pathFilter);

    Loop::onSignal(SIGINT, static function (string $watcherId) use ($hotReloadWatcher) {
        Loop::cancel($watcherId);

        yield $hotReloadWatcher->unwatch();
    });
});
