#!/usr/bin/env php
<?php

use Amp\File\StatCache;
use Amp\Loop;
use Vajexal\HotReload\HotReloadWatcher;
use Vajexal\HotReload\PathFilter\GlobPathFilter;

require_once 'vendor/autoload.php';

if (count($_SERVER['argv']) <= 1) {
    echo 'Usage: ./vendor/bin/hot-reload server.php', PHP_EOL;
    exit(1);
}

Loop::run(function () {
    StatCache::ttl(0);

    $pathFilter = new GlobPathFilter([
        'vendor',
        '.git',
        '.idea',
    ]);

    $hotReloadWatcher = new HotReloadWatcher('.', [PHP_BINARY, ...array_slice($_SERVER['argv'], 1)], $pathFilter);

    Loop::onSignal(SIGINT, static function (string $watcherId) use ($hotReloadWatcher) {
        Loop::cancel($watcherId);

        yield $hotReloadWatcher->unwatch();
    });
});
