name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ 7.4, 8.0 ]

    container: php:${{ matrix.php }}-zts

    steps:
      - name: Setup PHP
        run: |
          apt update -y
          apt install -y git curl zip libzip-dev libuv1-dev
          docker-php-ext-install pcntl zip
          pecl install parallel eio uv-0.2.4 && docker-php-ext-enable parallel eio uv || true
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-${{ matrix.php }}-
            composer-

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction \
          --ignore-platform-req=ext-parallel \
          --ignore-platform-req=ext-eio \
          --ignore-platform-req=ext-uv

      - name: Check code style
        run: vendor/bin/php-cs-fixer fix --config=.php_cs.dist --verbose --diff --dry-run
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1

      - name: Run tests
        run: vendor/bin/phpunit
